In [35]:
import pandas as pd
import os
from random import randint

In [36]:
path_output=os.path.join(os.getcwd(), '..', 'data', 'output')
path_trips=os.path.join(path_output, "Trips.csv")
path_hex_big=os.path.join(path_output, "hexagons-big-dresden.csv")

print(path_trips)

/home/jovyan/work/notebooks/../data/output/Trips.csv

In [37]:
df_trips = pd.read_csv(path_trips, index_col="Unnamed: 0")
df_hex_big = pd.read_csv(path_hex_big, index_col="Unnamed: 0")

display(df_trips,df_hex_big)

,p_bike_racks_start,p_spot_start,p_booked_bikes_start,p_place_type_start,datetime_start,b_number_start,p_uid_start,p_bikes_start,p_lat_start,b_electric_lock_start,...,1_demand_hex_small,1_agg_time,24_demand_end,24_demand_hex_big_end,24_demand_hex_small_end,24_agg_time_end,6_demand_end,6_demand_hex_big_end,6_demand_hex_small_end,6_agg_time_end
0,0,False,0,12,2019-01-20 00:07:00,93322,12098234,1,51.041798,False,...,2,2019-01-20 00:00:00,265,24,4,2019-01-20 00:00:00,45,6.0,1.0,2019-01-20 00:00:00
1,0,True,0,0,2019-01-20 00:05:00,93576,10299640,5,51.038210,False,...,2,2019-01-20 00:00:00,265,151,7,2019-01-20 00:00:00,45,30.0,1.0,2019-01-20 00:00:00
2,0,False,0,12,2019-01-20 00:00:00,93771,12095573,1,51.071262,False,...,2,2019-01-20 00:00:00,265,24,1,2019-01-20 00:00:00,45,6.0,1.0,2019-01-20 00:00:00
3,0,False,0,12,2019-01-20 00:26:00,93478,12098942,1,51.028163,False,...,1,2019-01-20 00:00:00,265,151,2,2019-01-20 00:00:00,45,30.0,1.0,2019-01-20 00:00:00
4,0,True,0,0,2019-01-20 00:29:00,93577,264599,1,51.044740,False,...,1,2019-01-20 00:00:00,265,151,6,2019-01-20 00:00:00,45,30.0,2.0,2019-01-20 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567434,0,True,0,0,2020-01-20 23:33:00,93824,73,1,51.065184,True,...,5,2020-01-20 23:00:00,1050,225,4,2020-01-20 00:00:00,254,84.0,1.0,2020-01-20 18:00:00
567435,0,True,0,0,2020-01-20 23:29:00,93908,11248297,3,51.043537,True,...,2,2020-01-20 23:00:00,1050,686,55,2020-01-20 00:00:00,254,127.0,7.0,2020-01-20 18:00:00
567436,0,True,0,0,2020-01-20 23:23:00,93629,4783708,4,51.034415,True,...,2,2020-01-20 23:00:00,1050,84,6,2020-01-20 00:00:00,254,18.0,1.0,2020-01-20 18:00:00
567437,0,True,0,0,2020-01-20 23:29:00,93857,310792,6,51.038466,True,...,2,2020-01-20 23:00:00,1050,225,7,2020-01-20 00:00:00,254,84.0,4.0,2020-01-20 18:00:00
567438,0,False,0,12,2020-01-20 23:36:00,93454,27150164,1,51.044302,True,...,2,2020-01-20 23:00:00,1050,225,7,2020-01-20 00:00:00,254,84.0,4.0,2020-01-20 18:00:00

     h3_hex_big_id                                           geometry
0  861f1b56fffffff  POLYGON ((13.66742002342611 51.15224433237433,...
1  861f1b547ffffff  POLYGON ((13.60046007155825 51.11305144151748,...
2  861f1b0b7ffffff  POLYGON ((13.75543874334306 51.13976093214367,...
3  861f1b55fffffff  POLYGON ((13.62149402016324 51.06140093438403,...
4  861f1b46fffffff  POLYGON ((13.79728558598622 51.03637274669753,...
5  861f1b097ffffff  POLYGON ((13.77637694704919 51.08808996190518,...
6  861f1b09fffffff  POLYGON ((13.86432751736583 51.07550117594182,...
7  861f1b467ffffff  POLYGON ((13.70939233335147 51.04892282240107,...
8  861f1b087ffffff  POLYGON ((13.84345217144361 51.12720543733009,...
9  861f1b54fffffff  POLYGON ((13.68842099374826 51.10060671369379,...

In [38]:
df_trips["datetime_start"] = pd.to_datetime(df_trips["datetime_start"])
df_trips["datetime_end"] = pd.to_datetime(df_trips["datetime_end"])
df_trips["24_agg_time"] = pd.to_datetime(df_trips["24_agg_time"])
df_trips["24_agg_time_end"] = pd.to_datetime(df_trips["24_agg_time_end"])
df_trips["1_agg_time"] = pd.to_datetime(df_trips["1_agg_time"])
df_trips.columns

Index(['p_bike_racks_start', 'p_spot_start', 'p_booked_bikes_start',
       'p_place_type_start', 'datetime_start', 'b_number_start', 'p_uid_start',
       'p_bikes_start', 'p_lat_start', 'b_electric_lock_start',
       'b_bike_type_start', 'p_name_start', 'p_free_racks_start',
       'b_lock_types_start', 'p_number_start', 'p_lng_start',
       'b_boardcomputer_start', 'p_maintenance_start', 'p_bike_racks_end',
       'p_spot_end', 'p_booked_bikes_end', 'p_place_type_end', 'datetime_end',
       'p_uid_end', 'p_bikes_end', 'p_lat_end', 'p_name_end',
       'p_free_racks_end', 'p_number_end', 'p_lng_end', 'p_maintenance_end',
       'air_deg', 'air_hum', 'rain_mm', 'rain_yn', 'sun_hour', 'wind_ms',
       'month_start', 'month_end', 'day_start', 'day_end', 'day_of_week_start',
       'day_of_week_end', 'hour_start', 'hour_end', 'day_of_year_start',
       'day_of_year_end', 'season', 'weekend', 'booking_date_start',
       'trip_duration', 'idle_time', 'h3_hex_small_id_start',
       'h3_hex_small_id_end', 'h3_hex_big_id_start', 'h3_hex_big_id_end',
       '24_demand', '24_demand_hex_big', '24_demand_hex_small', '24_agg_time',
       '6_demand', '6_demand_hex_big', '6_demand_hex_small', '6_agg_time',
       '2_demand', '2_demand_hex_big', '2_demand_hex_small', '2_agg_time',
       '1_demand', '1_demand_hex_big', '1_demand_hex_small', '1_agg_time',
       '24_demand_end', '24_demand_hex_big_end', '24_demand_hex_small_end',
       '24_agg_time_end', '6_demand_end', '6_demand_hex_big_end',
       '6_demand_hex_small_end', '6_agg_time_end'],
      dtype='object')

In [39]:
# CONSTANTS
CUR_HEX = "861f1b097ffffff"
CUR_AGG_TIME = pd.to_datetime("2019-01-20")

In [40]:
def calculate_idle_available(df_trips, cur_hex, cur_agg_time):
    """
    # print("Calculating idle and available bikes for hexagon", cur_hex, "during aggregation time period", cur_agg_time)
    
    # === 1: CALCULATE IDLE BIKES ===
    # get all trips ending in current hexagon
    df_current_hex = df_trips[df_trips["h3_hex_big_id_end"] == cur_hex]
    # get all trips ending before beginning of aggregation time
    df_end_before_agg_time = df_current_hex[df_current_hex["datetime_end"] < cur_agg_time]
    # groupby bikenumber and get latest trip ending befor aggr time (= number of bikes that are in hexagon when aggr time begins)
    bikes_before = df_end_before_agg_time.groupby("b_number_start")["datetime_end"].max().count()
    
    # get all trips starting in current hexagon
    df_current_hex_start = df_trips[df_trips["h3_hex_big_id_start"] == cur_hex]
    # get all trips starting after aggregation time
    df_start_before_agg_time_end = df_current_hex_start[df_current_hex_start["24_agg_time"] == cur_agg_time]
    # count number of bikes started after aggregation time
    bikes_used_in_agg_time = df_start_before_agg_time_end.groupby("b_number_start")["datetime_start"].count().count()
    # print("bikes_used_in_agg_time",bikes_used_in_agg_time)
    
    # idle bikes = number of bikes when aggr time starts - number of bikes used after aggr time ends
    # (so inside aggr time period they were not used)
    idle_bikes = bikes_before - bikes_used_in_agg_time
    # print("Idle bikes:", idle_bikes)
    
    # === 2: CALCULATE AVAILABLE BIKES ===
    # get number of bikes started in current hexagon during current agg time
    df_trips_started = df_trips[(df_trips["24_agg_time"] == cur_agg_time) & (df_trips["h3_hex_big_id_start"] == cur_hex)]["24_demand_hex_big"]
    if (len(df_trips_started) == 0):
        trips_started = 0
    else:
        trips_started = df_trips_started.iloc[0]
    # print("Trips started (in current hexagon, during current agg time):",trips_started)
    # get number of trips ended in current hexagon during current agg time
    df_trips_ended = df_trips[(df_trips["24_agg_time_end"] == cur_agg_time) & (df_trips["h3_hex_big_id_end"] == cur_hex)]["24_demand_hex_big_end"]
    if (len(df_trips_ended) == 0):
        trips_ended = 0
    else:
        trips_ended = df_trips_ended.iloc[0]
    # print("Trips ended (in current hexagon, during current agg time):",trips_ended)
    
    # calculate available bikes for current hexagon & time period
    available_bikes = trips_ended - trips_started + idle_bikes
    # print("Available bikes:", available_bikes)
    """
    
    # """
    # === DISCLAIMER ===
    # As the calculations above throw out negative values for idle bikes and available bikes we assume that we have some mistake in our calculation.
    # To be able to show the systematics and understanding of the following training and prediction algorithms,
    # we decided to set random values in a range from [0 to 200] as idle bikes
    # and random values in a range from [0 to 500] as availability of bikes
    # With these random values, we will work from here on with the further algorithms.
    
    idle_bikes = randint(0,200)
    available_bikes = randint(0,500)
    # """
    
    # add newly calculated values to corresponding entries in trips data
    df_trips.loc[(df_trips["24_agg_time_end"] == cur_agg_time) & (df_trips["h3_hex_big_id_end"] == cur_hex),"24_idle_hex_big"]=idle_bikes
    df_trips.loc[(df_trips["24_agg_time_end"] == cur_agg_time) & (df_trips["h3_hex_big_id_end"] == cur_hex),"24_available_hex_big"]=available_bikes
    
    return df_trips

In [41]:
hex_big_ids = df_hex_big["h3_hex_big_id"].unique().tolist()
all_agg_times = df_trips["24_agg_time"].unique()
all_agg_times = pd.to_datetime(all_agg_times)
display(hex_big_ids, all_agg_times)

['861f1b56fffffff',
 '861f1b547ffffff',
 '861f1b0b7ffffff',
 '861f1b55fffffff',
 '861f1b46fffffff',
 '861f1b097ffffff',
 '861f1b09fffffff',
 '861f1b467ffffff',
 '861f1b087ffffff',
 '861f1b54fffffff']

DatetimeIndex(['2019-01-20', '2019-01-21', '2019-01-22', '2019-01-23',
               '2019-01-24', '2019-01-25', '2019-01-26', '2019-01-27',
               '2019-01-28', '2019-01-29',
               ...
               '2020-01-11', '2020-01-12', '2020-01-13', '2020-01-14',
               '2020-01-15', '2020-01-16', '2020-01-17', '2020-01-18',
               '2020-01-19', '2020-01-20'],
              dtype='datetime64[ns]', length=363, freq=None)

In [42]:
df_trips = calculate_idle_available(df_trips=df_trips, cur_hex=CUR_HEX, cur_agg_time=CUR_AGG_TIME)
df_trips[df_trips["24_agg_time_end"] == CUR_AGG_TIME]

,p_bike_racks_start,p_spot_start,p_booked_bikes_start,p_place_type_start,datetime_start,b_number_start,p_uid_start,p_bikes_start,p_lat_start,b_electric_lock_start,...,24_demand_end,24_demand_hex_big_end,24_demand_hex_small_end,24_agg_time_end,6_demand_end,6_demand_hex_big_end,6_demand_hex_small_end,6_agg_time_end,24_idle_hex_big,24_available_hex_big
0,0,False,0,12,2019-01-20 00:07:00,93322,12098234,1,51.041798,False,...,265,24,4,2019-01-20,45,6.0,1.0,2019-01-20 00:00:00,NaN,NaN
1,0,True,0,0,2019-01-20 00:05:00,93576,10299640,5,51.038210,False,...,265,151,7,2019-01-20,45,30.0,1.0,2019-01-20 00:00:00,NaN,NaN
2,0,False,0,12,2019-01-20 00:00:00,93771,12095573,1,51.071262,False,...,265,24,1,2019-01-20,45,6.0,1.0,2019-01-20 00:00:00,NaN,NaN
3,0,False,0,12,2019-01-20 00:26:00,93478,12098942,1,51.028163,False,...,265,151,2,2019-01-20,45,30.0,1.0,2019-01-20 00:00:00,NaN,NaN
4,0,True,0,0,2019-01-20 00:29:00,93577,264599,1,51.044740,False,...,265,151,6,2019-01-20,45,30.0,2.0,2019-01-20 00:00:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,0,True,0,0,2019-01-20 21:54:00,93769,10299678,2,51.023416,False,...,265,151,9,2019-01-20,68,34.0,5.0,2019-01-20 18:00:00,NaN,NaN
261,0,False,0,12,2019-01-20 21:52:00,93011,12098642,1,51.042946,False,...,265,151,19,2019-01-20,68,34.0,4.0,2019-01-20 18:00:00,NaN,NaN
262,6,True,0,0,2019-01-20 12:12:00,93777,329097,5,51.051370,False,...,265,25,6,2019-01-20,68,7.0,5.0,2019-01-20 12:00:00,175.0,333.0
263,0,True,0,0,2019-01-20 22:51:00,93704,14262,3,51.074983,False,...,265,63,12,2019-01-20,68,22.0,4.0,2019-01-20 18:00:00,NaN,NaN
264,0,True,0,0,2019-01-20 23:36:00,93538,10299537,3,51.050166,False,...,265,24,8,2019-01-20,68,4.0,2.0,2019-01-20 18:00:00,NaN,NaN

In [43]:
for hex_id in hex_big_ids:
    print("Hexagon is:", hex_id)
    for agg_time in all_agg_times:
        df_trips = calculate_idle_available(df_trips=df_trips, cur_hex=hex_id, cur_agg_time=agg_time)

df_trips

Hexagon is: 861f1b56fffffff
Hexagon is: 861f1b547ffffff
Hexagon is: 861f1b0b7ffffff
Hexagon is: 861f1b55fffffff
Hexagon is: 861f1b46fffffff
Hexagon is: 861f1b097ffffff
Hexagon is: 861f1b09fffffff
Hexagon is: 861f1b467ffffff
Hexagon is: 861f1b087ffffff
Hexagon is: 861f1b54fffffff

,p_bike_racks_start,p_spot_start,p_booked_bikes_start,p_place_type_start,datetime_start,b_number_start,p_uid_start,p_bikes_start,p_lat_start,b_electric_lock_start,...,24_demand_end,24_demand_hex_big_end,24_demand_hex_small_end,24_agg_time_end,6_demand_end,6_demand_hex_big_end,6_demand_hex_small_end,6_agg_time_end,24_idle_hex_big,24_available_hex_big
0,0,False,0,12,2019-01-20 00:07:00,93322,12098234,1,51.041798,False,...,265,24,4,2019-01-20,45,6.0,1.0,2019-01-20 00:00:00,94.0,447.0
1,0,True,0,0,2019-01-20 00:05:00,93576,10299640,5,51.038210,False,...,265,151,7,2019-01-20,45,30.0,1.0,2019-01-20 00:00:00,121.0,39.0
2,0,False,0,12,2019-01-20 00:00:00,93771,12095573,1,51.071262,False,...,265,24,1,2019-01-20,45,6.0,1.0,2019-01-20 00:00:00,94.0,447.0
3,0,False,0,12,2019-01-20 00:26:00,93478,12098942,1,51.028163,False,...,265,151,2,2019-01-20,45,30.0,1.0,2019-01-20 00:00:00,121.0,39.0
4,0,True,0,0,2019-01-20 00:29:00,93577,264599,1,51.044740,False,...,265,151,6,2019-01-20,45,30.0,2.0,2019-01-20 00:00:00,121.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567434,0,True,0,0,2020-01-20 23:33:00,93824,73,1,51.065184,True,...,1050,225,4,2020-01-20,254,84.0,1.0,2020-01-20 18:00:00,199.0,261.0
567435,0,True,0,0,2020-01-20 23:29:00,93908,11248297,3,51.043537,True,...,1050,686,55,2020-01-20,254,127.0,7.0,2020-01-20 18:00:00,191.0,362.0
567436,0,True,0,0,2020-01-20 23:23:00,93629,4783708,4,51.034415,True,...,1050,84,6,2020-01-20,254,18.0,1.0,2020-01-20 18:00:00,2.0,449.0
567437,0,True,0,0,2020-01-20 23:29:00,93857,310792,6,51.038466,True,...,1050,225,7,2020-01-20,254,84.0,4.0,2020-01-20 18:00:00,199.0,261.0
567438,0,False,0,12,2020-01-20 23:36:00,93454,27150164,1,51.044302,True,...,1050,225,7,2020-01-20,254,84.0,4.0,2020-01-20 18:00:00,199.0,261.0

In [44]:
print(df_trips["24_idle_hex_big"].isna().sum().sum())
print(df_trips["24_available_hex_big"].isna().sum().sum())

724
724

In [45]:
df_trips[df_trips["24_available_hex_big"] < 0]["24_agg_time_end"].unique()

array([], dtype='datetime64[ns]')

In [46]:
avg_idle = int(df_trips["24_idle_hex_big"].mean())
df_trips["24_idle_hex_big"].fillna(avg_available, inplace=True)
avg_available = int(df_trips["24_available_hex_big"].mean())
df_trips["24_available_hex_big"].fillna(avg_available, inplace=True)
print(df_trips["24_idle_hex_big"].isna().sum().sum())
print(df_trips["24_available_hex_big"].isna().sum().sum())

0
0

In [47]:
df_trips.to_csv(os.path.join(path_output, "Trips.csv"))