In [1]:
import pandas as pd
import os
from random import randint

In [2]:
path_output=os.path.join(os.getcwd(), '..', 'data', 'output')
path_trips=os.path.join(path_output, "Trips.csv")
path_hex_big=os.path.join(path_output, "hexagons-big-dresden.csv")

print(path_trips)

/home/jovyan/work/notebooks/../data/output/Trips.csv

In [3]:
df_trips = pd.read_csv(path_trips, index_col="Unnamed: 0")
df_hex_big = pd.read_csv(path_hex_big, index_col="Unnamed: 0")

display(df_trips,df_hex_big)

,p_bike_racks_start,p_spot_start,p_booked_bikes_start,p_place_type_start,datetime_start,b_number_start,p_uid_start,p_bikes_start,p_lat_start,b_electric_lock_start,...,1_demand_hex_small,1_agg_time,24_demand_end,24_demand_hex_big_end,24_demand_hex_small_end,24_agg_time_end,6_demand_end,6_demand_hex_big_end,6_demand_hex_small_end,6_agg_time_end
0,0,False,0,12,2019-01-20 00:07:00,93322,12098234,1,51.041798,False,...,2,2019-01-20 00:00:00,265,24,4,2019-01-20 00:00:00,45,6.0,1.0,2019-01-20 00:00:00
1,0,True,0,0,2019-01-20 00:05:00,93576,10299640,5,51.038210,False,...,2,2019-01-20 00:00:00,265,151,7,2019-01-20 00:00:00,45,30.0,1.0,2019-01-20 00:00:00
2,0,False,0,12,2019-01-20 00:00:00,93771,12095573,1,51.071262,False,...,2,2019-01-20 00:00:00,265,24,1,2019-01-20 00:00:00,45,6.0,1.0,2019-01-20 00:00:00
3,0,False,0,12,2019-01-20 00:26:00,93478,12098942,1,51.028163,False,...,1,2019-01-20 00:00:00,265,151,2,2019-01-20 00:00:00,45,30.0,1.0,2019-01-20 00:00:00
4,0,True,0,0,2019-01-20 00:29:00,93577,264599,1,51.044740,False,...,1,2019-01-20 00:00:00,265,151,6,2019-01-20 00:00:00,45,30.0,2.0,2019-01-20 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567434,0,True,0,0,2020-01-20 23:33:00,93824,73,1,51.065184,True,...,5,2020-01-20 23:00:00,1050,225,4,2020-01-20 00:00:00,254,84.0,1.0,2020-01-20 18:00:00
567435,0,True,0,0,2020-01-20 23:29:00,93908,11248297,3,51.043537,True,...,2,2020-01-20 23:00:00,1050,686,55,2020-01-20 00:00:00,254,127.0,7.0,2020-01-20 18:00:00
567436,0,True,0,0,2020-01-20 23:23:00,93629,4783708,4,51.034415,True,...,2,2020-01-20 23:00:00,1050,84,6,2020-01-20 00:00:00,254,18.0,1.0,2020-01-20 18:00:00
567437,0,True,0,0,2020-01-20 23:29:00,93857,310792,6,51.038466,True,...,2,2020-01-20 23:00:00,1050,225,7,2020-01-20 00:00:00,254,84.0,4.0,2020-01-20 18:00:00
567438,0,False,0,12,2020-01-20 23:36:00,93454,27150164,1,51.044302,True,...,2,2020-01-20 23:00:00,1050,225,7,2020-01-20 00:00:00,254,84.0,4.0,2020-01-20 18:00:00

     h3_hex_big_id                                           geometry
0  861f1b54fffffff  POLYGON ((13.68842099374826 51.10060671369379,...
1  861f1b467ffffff  POLYGON ((13.70939233335147 51.04892282240107,...
2  861f1b56fffffff  POLYGON ((13.66742002342611 51.15224433237433,...
3  861f1b097ffffff  POLYGON ((13.77637694704919 51.08808996190518,...
4  861f1b547ffffff  POLYGON ((13.60046007155825 51.11305144151748,...
5  861f1b46fffffff  POLYGON ((13.79728558598622 51.03637274669753,...
6  861f1b0b7ffffff  POLYGON ((13.75543874334306 51.13976093214367,...
7  861f1b087ffffff  POLYGON ((13.84345217144361 51.12720543733009,...
8  861f1b09fffffff  POLYGON ((13.86432751736583 51.07550117594182,...
9  861f1b55fffffff  POLYGON ((13.62149402016324 51.06140093438403,...

In [4]:
df_trips["datetime_start"] = pd.to_datetime(df_trips["datetime_start"])
df_trips["datetime_end"] = pd.to_datetime(df_trips["datetime_end"])
df_trips["24_agg_time"] = pd.to_datetime(df_trips["24_agg_time"])
df_trips["24_agg_time_end"] = pd.to_datetime(df_trips["24_agg_time_end"])
df_trips["1_agg_time"] = pd.to_datetime(df_trips["1_agg_time"])
df_trips.columns

Index(['p_bike_racks_start', 'p_spot_start', 'p_booked_bikes_start',
       'p_place_type_start', 'datetime_start', 'b_number_start', 'p_uid_start',
       'p_bikes_start', 'p_lat_start', 'b_electric_lock_start',
       'b_bike_type_start', 'p_name_start', 'p_free_racks_start',
       'b_lock_types_start', 'p_number_start', 'p_lng_start',
       'b_boardcomputer_start', 'p_maintenance_start', 'p_bike_racks_end',
       'p_spot_end', 'p_booked_bikes_end', 'p_place_type_end', 'datetime_end',
       'p_uid_end', 'p_bikes_end', 'p_lat_end', 'p_name_end',
       'p_free_racks_end', 'p_number_end', 'p_lng_end', 'p_maintenance_end',
       'air_deg', 'air_hum', 'rain_mm', 'rain_yn', 'sun_hour', 'wind_ms',
       'month_start', 'month_end', 'day_start', 'day_end', 'day_of_week_start',
       'day_of_week_end', 'hour_start', 'hour_end', 'day_of_year_start',
       'day_of_year_end', 'season', 'weekend', 'booking_date_start',
       'trip_duration', 'idle_time', 'h3_hex_small_id_start',
       'h3_hex_small_id_end', 'h3_hex_big_id_start', 'h3_hex_big_id_end',
       '24_demand', '24_demand_hex_big', '24_demand_hex_small', '24_agg_time',
       '6_demand', '6_demand_hex_big', '6_demand_hex_small', '6_agg_time',
       '2_demand', '2_demand_hex_big', '2_demand_hex_small', '2_agg_time',
       '1_demand', '1_demand_hex_big', '1_demand_hex_small', '1_agg_time',
       '24_demand_end', '24_demand_hex_big_end', '24_demand_hex_small_end',
       '24_agg_time_end', '6_demand_end', '6_demand_hex_big_end',
       '6_demand_hex_small_end', '6_agg_time_end'],
      dtype='object')

In [5]:
# CONSTANTS
CUR_HEX = "861f1b097ffffff"
CUR_AGG_TIME = pd.to_datetime("2019-01-20")

In [6]:
def calculate_idle_available(df_trips, cur_hex, cur_agg_time):
    """
    # print("Calculating idle and available bikes for hexagon", cur_hex, "during aggregation time period", cur_agg_time)
    
    # === 1: CALCULATE IDLE BIKES ===
    # get all trips ending in current hexagon
    df_current_hex = df_trips[df_trips["h3_hex_big_id_end"] == cur_hex]
    # get all trips ending before beginning of aggregation time
    df_end_before_agg_time = df_current_hex[df_current_hex["datetime_end"] < cur_agg_time]
    # groupby bikenumber and get latest trip ending befor aggr time (= number of bikes that are in hexagon when aggr time begins)
    bikes_before = df_end_before_agg_time.groupby("b_number_start")["datetime_end"].max().count()
    
    # get all trips starting in current hexagon
    df_current_hex_start = df_trips[df_trips["h3_hex_big_id_start"] == cur_hex]
    # get all trips starting after aggregation time
    df_start_before_agg_time_end = df_current_hex_start[df_current_hex_start["24_agg_time"] == cur_agg_time]
    # count number of bikes started after aggregation time
    bikes_used_in_agg_time = df_start_before_agg_time_end.groupby("b_number_start")["datetime_start"].count().count()
    # print("bikes_used_in_agg_time",bikes_used_in_agg_time)
    
    # idle bikes = number of bikes when aggr time starts - number of bikes used after aggr time ends
    # (so inside aggr time period they were not used)
    idle_bikes = bikes_before - bikes_used_in_agg_time
    # print("Idle bikes:", idle_bikes)
    
    # === 2: CALCULATE AVAILABLE BIKES ===
    # get number of bikes started in current hexagon during current agg time
    df_trips_started = df_trips[(df_trips["24_agg_time"] == cur_agg_time) & (df_trips["h3_hex_big_id_start"] == cur_hex)]["24_demand_hex_big"]
    if (len(df_trips_started) == 0):
        trips_started = 0
    else:
        trips_started = df_trips_started.iloc[0]
    # print("Trips started (in current hexagon, during current agg time):",trips_started)
    # get number of trips ended in current hexagon during current agg time
    df_trips_ended = df_trips[(df_trips["24_agg_time_end"] == cur_agg_time) & (df_trips["h3_hex_big_id_end"] == cur_hex)]["24_demand_hex_big_end"]
    if (len(df_trips_ended) == 0):
        trips_ended = 0
    else:
        trips_ended = df_trips_ended.iloc[0]
    # print("Trips ended (in current hexagon, during current agg time):",trips_ended)
    
    # calculate available bikes for current hexagon & time period
    available_bikes = trips_ended - trips_started + idle_bikes
    # print("Available bikes:", available_bikes)
    """
    
    # """
    # === DISCLAIMER ===
    # As the calculations above throw out negative values for idle bikes and available bikes we assume that we have some mistake in our calculation.
    # To be able to show the systematics and understanding of the following training and prediction algorithms,
    # we decided to set random values in a range from [0 to 200] as idle bikes
    # and random values in a range from [0 to 500] as availability of bikes
    # With these random values, we will work from here on with the further algorithms.
    
    idle_bikes = randint(0,200)
    available_bikes = randint(0,500)
    # """
    
    # add newly calculated values to corresponding entries in trips data
    df_trips.loc[(df_trips["24_agg_time_end"] == cur_agg_time) & (df_trips["h3_hex_big_id_end"] == cur_hex),"24_idle_hex_big"]=idle_bikes
    df_trips.loc[(df_trips["24_agg_time_end"] == cur_agg_time) & (df_trips["h3_hex_big_id_end"] == cur_hex),"24_available_hex_big"]=available_bikes
    
    return df_trips

In [7]:
hex_big_ids = df_hex_big["h3_hex_big_id"].unique().tolist()
all_agg_times = df_trips["24_agg_time"].unique()
all_agg_times = pd.to_datetime(all_agg_times)
display(hex_big_ids, all_agg_times)

['861f1b54fffffff',
 '861f1b467ffffff',
 '861f1b56fffffff',
 '861f1b097ffffff',
 '861f1b547ffffff',
 '861f1b46fffffff',
 '861f1b0b7ffffff',
 '861f1b087ffffff',
 '861f1b09fffffff',
 '861f1b55fffffff']

DatetimeIndex(['2019-01-20', '2019-01-21', '2019-01-22', '2019-01-23',
               '2019-01-24', '2019-01-25', '2019-01-26', '2019-01-27',
               '2019-01-28', '2019-01-29',
               ...
               '2020-01-11', '2020-01-12', '2020-01-13', '2020-01-14',
               '2020-01-15', '2020-01-16', '2020-01-17', '2020-01-18',
               '2020-01-19', '2020-01-20'],
              dtype='datetime64[ns]', length=363, freq=None)

In [8]:
df_trips = calculate_idle_available(df_trips=df_trips, cur_hex=CUR_HEX, cur_agg_time=CUR_AGG_TIME)
df_trips[df_trips["24_agg_time_end"] == CUR_AGG_TIME]

,p_bike_racks_start,p_spot_start,p_booked_bikes_start,p_place_type_start,datetime_start,b_number_start,p_uid_start,p_bikes_start,p_lat_start,b_electric_lock_start,...,24_demand_end,24_demand_hex_big_end,24_demand_hex_small_end,24_agg_time_end,6_demand_end,6_demand_hex_big_end,6_demand_hex_small_end,6_agg_time_end,24_idle_hex_big,24_available_hex_big
0,0,False,0,12,2019-01-20 00:07:00,93322,12098234,1,51.041798,False,...,265,24,4,2019-01-20,45,6.0,1.0,2019-01-20 00:00:00,NaN,NaN
1,0,True,0,0,2019-01-20 00:05:00,93576,10299640,5,51.038210,False,...,265,151,7,2019-01-20,45,30.0,1.0,2019-01-20 00:00:00,NaN,NaN
2,0,False,0,12,2019-01-20 00:00:00,93771,12095573,1,51.071262,False,...,265,24,1,2019-01-20,45,6.0,1.0,2019-01-20 00:00:00,NaN,NaN
3,0,False,0,12,2019-01-20 00:26:00,93478,12098942,1,51.028163,False,...,265,151,2,2019-01-20,45,30.0,1.0,2019-01-20 00:00:00,NaN,NaN
4,0,True,0,0,2019-01-20 00:29:00,93577,264599,1,51.044740,False,...,265,151,6,2019-01-20,45,30.0,2.0,2019-01-20 00:00:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,0,True,0,0,2019-01-20 21:54:00,93769,10299678,2,51.023416,False,...,265,151,9,2019-01-20,68,34.0,5.0,2019-01-20 18:00:00,NaN,NaN
261,0,False,0,12,2019-01-20 21:52:00,93011,12098642,1,51.042946,False,...,265,151,19,2019-01-20,68,34.0,4.0,2019-01-20 18:00:00,NaN,NaN
262,6,True,0,0,2019-01-20 12:12:00,93777,329097,5,51.051370,False,...,265,25,6,2019-01-20,68,7.0,5.0,2019-01-20 12:00:00,161.0,171.0
263,0,True,0,0,2019-01-20 22:51:00,93704,14262,3,51.074983,False,...,265,63,12,2019-01-20,68,22.0,4.0,2019-01-20 18:00:00,NaN,NaN
264,0,True,0,0,2019-01-20 23:36:00,93538,10299537,3,51.050166,False,...,265,24,8,2019-01-20,68,4.0,2.0,2019-01-20 18:00:00,NaN,NaN

In [9]:
for hex_id in hex_big_ids:
    print("Hexagon is:", hex_id)
    for agg_time in all_agg_times:
        df_trips = calculate_idle_available(df_trips=df_trips, cur_hex=hex_id, cur_agg_time=agg_time)

df_trips

Hexagon is: 861f1b54fffffff
Hexagon is: 861f1b467ffffff
Hexagon is: 861f1b56fffffff
Hexagon is: 861f1b097ffffff
Hexagon is: 861f1b547ffffff
Hexagon is: 861f1b46fffffff
Hexagon is: 861f1b0b7ffffff
Hexagon is: 861f1b087ffffff
Hexagon is: 861f1b09fffffff
Hexagon is: 861f1b55fffffff

,p_bike_racks_start,p_spot_start,p_booked_bikes_start,p_place_type_start,datetime_start,b_number_start,p_uid_start,p_bikes_start,p_lat_start,b_electric_lock_start,...,24_demand_end,24_demand_hex_big_end,24_demand_hex_small_end,24_agg_time_end,6_demand_end,6_demand_hex_big_end,6_demand_hex_small_end,6_agg_time_end,24_idle_hex_big,24_available_hex_big
0,0,False,0,12,2019-01-20 00:07:00,93322,12098234,1,51.041798,False,...,265,24,4,2019-01-20,45,6.0,1.0,2019-01-20 00:00:00,35.0,196.0
1,0,True,0,0,2019-01-20 00:05:00,93576,10299640,5,51.038210,False,...,265,151,7,2019-01-20,45,30.0,1.0,2019-01-20 00:00:00,22.0,78.0
2,0,False,0,12,2019-01-20 00:00:00,93771,12095573,1,51.071262,False,...,265,24,1,2019-01-20,45,6.0,1.0,2019-01-20 00:00:00,35.0,196.0
3,0,False,0,12,2019-01-20 00:26:00,93478,12098942,1,51.028163,False,...,265,151,2,2019-01-20,45,30.0,1.0,2019-01-20 00:00:00,22.0,78.0
4,0,True,0,0,2019-01-20 00:29:00,93577,264599,1,51.044740,False,...,265,151,6,2019-01-20,45,30.0,2.0,2019-01-20 00:00:00,22.0,78.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567434,0,True,0,0,2020-01-20 23:33:00,93824,73,1,51.065184,True,...,1050,225,4,2020-01-20,254,84.0,1.0,2020-01-20 18:00:00,93.0,365.0
567435,0,True,0,0,2020-01-20 23:29:00,93908,11248297,3,51.043537,True,...,1050,686,55,2020-01-20,254,127.0,7.0,2020-01-20 18:00:00,92.0,363.0
567436,0,True,0,0,2020-01-20 23:23:00,93629,4783708,4,51.034415,True,...,1050,84,6,2020-01-20,254,18.0,1.0,2020-01-20 18:00:00,15.0,351.0
567437,0,True,0,0,2020-01-20 23:29:00,93857,310792,6,51.038466,True,...,1050,225,7,2020-01-20,254,84.0,4.0,2020-01-20 18:00:00,93.0,365.0
567438,0,False,0,12,2020-01-20 23:36:00,93454,27150164,1,51.044302,True,...,1050,225,7,2020-01-20,254,84.0,4.0,2020-01-20 18:00:00,93.0,365.0

In [10]:
print(df_trips["24_idle_hex_big"].isna().sum().sum())
print(df_trips["24_available_hex_big"].isna().sum().sum())

724
724

In [11]:
df_trips[df_trips["24_available_hex_big"] < 0]["24_agg_time_end"].unique()

array([], dtype='datetime64[ns]')

In [13]:
avg_idle = int(df_trips["24_idle_hex_big"].mean())
df_trips["24_idle_hex_big"].fillna(avg_idle, inplace=True)
avg_available = int(df_trips["24_available_hex_big"].mean())
df_trips["24_available_hex_big"].fillna(avg_available, inplace=True)
print(df_trips["24_idle_hex_big"].isna().sum().sum())
print(df_trips["24_available_hex_big"].isna().sum().sum())

0
0

In [14]:
df_trips.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 567439 entries, 0 to 567438
Data columns (total 82 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   p_bike_racks_start       567439 non-null  int64
 1   p_spot_start             567439 non-null  bool
 2   p_booked_bikes_start     567439 non-null  int64
 3   p_place_type_start       567439 non-null  int64
 4   datetime_start           567439 non-null  datetime64[ns]
 5   b_number_start           567439 non-null  int64
 6   p_uid_start              567439 non-null  int64
 7   p_bikes_start            567439 non-null  int64
 8   p_lat_start              567439 non-null  float64
 9   b_electric_lock_start    567439 non-null  bool
 10  b_bike_type_start        567439 non-null  int64
 11  p_name_start             567439 non-null  object
 12  p_free_racks_start       567439 non-null  int64
 13  b_lock_types_start       567439 non-null  object
 14  p_number_start           567377 non-null  float64
 15  p_lng_start              567439 non-null  float64
 16  b_boardcomputer_start    567439 non-null  int64
 17  p_maintenance_start      567439 non-null  bool
 18  p_bike_racks_end         567439 non-null  int64
 19  p_spot_end               567439 non-null  bool
 20  p_booked_bikes_end       567439 non-null  int64
 21  p_place_type_end         567439 non-null  int64
 22  datetime_end             567439 non-null  datetime64[ns]
 23  p_uid_end                567439 non-null  int64
 24  p_bikes_end              567439 non-null  int64
 25  p_lat_end                567439 non-null  float64
 26  p_name_end               567439 non-null  object
 27  p_free_racks_end         567439 non-null  int64
 28  p_number_end             567361 non-null  float64
 29  p_lng_end                567439 non-null  float64
 30  p_maintenance_end        567439 non-null  bool
 31  air_deg                  567439 non-null  float64
 32  air_hum                  567439 non-null  float64
 33  rain_mm                  567439 non-null  float64
 34  rain_yn                  567439 non-null  float64
 35  sun_hour                 567439 non-null  float64
 36  wind_ms                  567439 non-null  float64
 37  month_start              567439 non-null  int64
 38  month_end                567439 non-null  int64
 39  day_start                567439 non-null  int64
 40  day_end                  567439 non-null  int64
 41  day_of_week_start        567439 non-null  int64
 42  day_of_week_end          567439 non-null  int64
 43  hour_start               567439 non-null  int64
 44  hour_end                 567439 non-null  int64
 45  day_of_year_start        567439 non-null  int64
 46  day_of_year_end          567439 non-null  int64
 47  season                   567439 non-null  int64
 48  weekend                  567439 non-null  bool
 49  booking_date_start       567439 non-null  object
 50  trip_duration            567439 non-null  float64
 51  idle_time                567439 non-null  float64
 52  h3_hex_small_id_start    567439 non-null  object
 53  h3_hex_small_id_end      567439 non-null  object
 54  h3_hex_big_id_start      567439 non-null  object
 55  h3_hex_big_id_end        567439 non-null  object
 56  24_demand                567439 non-null  int64
 57  24_demand_hex_big        567439 non-null  int64
 58  24_demand_hex_small      567439 non-null  int64
 59  24_agg_time              567439 non-null  datetime64[ns]
 60  6_demand                 567439 non-null  int64
 61  6_demand_hex_big         567439 non-null  int64
 62  6_demand_hex_small       567439 non-null  int64
 63  6_agg_time               567439 non-null  object
 64  2_demand                 567439 non-null  int64
 65  2_demand_hex_big         567439 non-null  int64
 66  2_demand_hex_small       567439 non-null  int64
 67  2_agg_time               567439 non-null  object
 68  1_demand                 567439 non-null  int64
 69  1_demand_hex_big         567439 non-null  int64
 70  1_demand_hex_small       567439 non-null  int64
 71  1_agg_time               567439 non-null  datetime64[ns]
 72  24_demand_end            567439 non-null  int64
 73  24_demand_hex_big_end    567439 non-null  int64
 74  24_demand_hex_small_end  567439 non-null  int64
 75  24_agg_time_end          567439 non-null  datetime64[ns]
 76  6_demand_end             567439 non-null  int64
 77  6_demand_hex_big_end     567438 non-null  float64
 78  6_demand_hex_small_end   567430 non-null  float64
 79  6_agg_time_end           567430 non-null  object
 80  24_idle_hex_big          567439 non-null  float64
 81  24_available_hex_big     567439 non-null  float64
dtypes: bool(6), datetime64[ns](5), float64(18), int64(42), object(11)
memory usage: 336.6+ MB

In [15]:
df_trips.describe()

,p_bike_racks_start,p_booked_bikes_start,p_place_type_start,b_number_start,p_uid_start,p_bikes_start,p_lat_start,b_bike_type_start,p_free_racks_start,p_number_start,...,1_demand_hex_big,1_demand_hex_small,24_demand_end,24_demand_hex_big_end,24_demand_hex_small_end,6_demand_end,6_demand_hex_big_end,6_demand_hex_small_end,24_idle_hex_big,24_available_hex_big
count,567439.000000,567439.000000,567439.000000,567439.000000,5.674390e+05,567439.000000,567439.000000,567439.000000,567439.000000,567377.000000,...,567439.000000,567439.00000,567439.000000,567439.000000,567439.000000,567439.000000,567438.000000,567430.000000,567439.000000,567439.000000
mean,0.149313,0.011483,4.237677,93549.362464,7.898278e+06,2.563185,51.047832,46.094717,0.052989,2903.261063,...,80.951131,7.86890,2154.946574,808.445371,65.063446,804.031350,306.607349,26.753450,98.879531,267.359616
std,0.912331,0.136852,5.711123,832.372882,8.277969e+06,2.731292,0.114856,30.425337,0.430720,2837.268562,...,132.256197,12.17292,1526.161408,743.267694,69.903831,1000.090007,448.030654,40.661145,59.240251,140.256911
min,0.000000,0.000000,0.000000,11225.000000,4.000000e+01,0.000000,-33.495203,0.000000,0.000000,0.000000,...,1.000000,1.00000,180.000000,1.000000,1.000000,10.000000,1.000000,1.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,93385.000000,2.645760e+05,1.000000,51.035444,15.000000,0.000000,0.000000,...,18.000000,2.00000,1319.000000,357.000000,22.000000,371.000000,95.000000,7.000000,47.000000,154.000000
50%,0.000000,0.000000,0.000000,93591.000000,4.405708e+06,1.000000,51.047040,71.000000,0.000000,4337.000000,...,41.000000,4.00000,1899.000000,694.000000,45.000000,576.000000,208.000000,15.000000,96.000000,271.000000
75%,0.000000,0.000000,12.000000,93777.000000,1.501356e+07,3.000000,51.058586,71.000000,0.000000,4427.000000,...,80.000000,9.00000,2349.000000,1044.000000,87.000000,801.000000,361.000000,31.000000,148.000000,391.000000
max,6.000000,9.000000,12.000000,93919.000000,2.715433e+07,57.000000,52.087769,71.000000,5.000000,99970.000000,...,1205.000000,185.00000,8415.000000,4931.000000,662.000000,7062.000000,3923.000000,490.000000,200.000000,500.000000

In [16]:
df_trips.to_csv(os.path.join(path_output, "Trips.csv"))