In [110]:
import pandas as pd
import os

In [111]:
path_trips=os.path.join(os.getcwd(), "..", "data", "output", "Trips.csv")

print(path_trips)

C:\Users\Max\github\AAA_Jupyter_Explorers\notebooks\..\data\output\Trips.csv

In [112]:
df_trips = pd.read_csv(path_trips, index_col="Unnamed: 0")
df_trips

,p_bike_racks_start,p_spot_start,p_booked_bikes_start,p_place_type_start,datetime_start,b_number_start,p_uid_start,p_bikes_start,p_lat_start,b_electric_lock_start,...,1_demand_hex_small,1_agg_time,24_demand_end,24_demand_hex_big_end,24_demand_hex_small_end,24_agg_time_end,6_demand_end,6_demand_hex_big_end,6_demand_hex_small_end,6_agg_time_end
0,0,False,0,12,2019-01-20 00:07:00,93322,12098234,1,51.041798,False,...,1,2019-01-20 00:00:00,265,4,1,2019-01-20 00:00:00,45,1.0,1.0,2019-01-20 00:00:00
1,0,True,0,0,2019-01-20 00:05:00,93576,10299640,5,51.038210,False,...,1,2019-01-20 00:00:00,265,7,7,2019-01-20 00:00:00,45,1.0,1.0,2019-01-20 00:00:00
2,0,False,0,12,2019-01-20 00:00:00,93771,12095573,1,51.071262,False,...,1,2019-01-20 00:00:00,265,1,3,2019-01-20 00:00:00,45,1.0,1.0,2019-01-20 00:00:00
3,0,False,0,12,2019-01-20 00:26:00,93478,12098942,1,51.028163,False,...,1,2019-01-20 00:00:00,265,2,2,2019-01-20 00:00:00,45,1.0,1.0,2019-01-20 00:00:00
4,0,True,0,0,2019-01-20 00:29:00,93577,264599,1,51.044740,False,...,1,2019-01-20 00:00:00,265,6,4,2019-01-20 00:00:00,45,2.0,2.0,2019-01-20 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567434,0,True,0,0,2020-01-20 23:33:00,93824,73,1,51.065184,True,...,2,2020-01-20 23:00:00,1050,4,3,2020-01-20 00:00:00,254,1.0,1.0,2020-01-20 18:00:00
567435,0,True,0,0,2020-01-20 23:29:00,93908,11248297,3,51.043537,True,...,1,2020-01-20 23:00:00,1050,55,28,2020-01-20 00:00:00,254,7.0,4.0,2020-01-20 18:00:00
567436,0,True,0,0,2020-01-20 23:23:00,93629,4783708,4,51.034415,True,...,1,2020-01-20 23:00:00,1050,6,4,2020-01-20 00:00:00,254,1.0,1.0,2020-01-20 18:00:00
567437,0,True,0,0,2020-01-20 23:29:00,93857,310792,6,51.038466,True,...,1,2020-01-20 23:00:00,1050,7,7,2020-01-20 00:00:00,254,4.0,4.0,2020-01-20 18:00:00
567438,0,False,0,12,2020-01-20 23:36:00,93454,27150164,1,51.044302,True,...,2,2020-01-20 23:00:00,1050,7,7,2020-01-20 00:00:00,254,4.0,4.0,2020-01-20 18:00:00

In [113]:
df_trips["datetime_start"] = pd.to_datetime(df_trips["datetime_start"])
df_trips["datetime_end"] = pd.to_datetime(df_trips["datetime_end"])
df_trips["24_agg_time"] = pd.to_datetime(df_trips["24_agg_time"])
df_trips["1_agg_time"] = pd.to_datetime(df_trips["1_agg_time"])
df_trips.columns

Index(['p_bike_racks_start', 'p_spot_start', 'p_booked_bikes_start',
       'p_place_type_start', 'datetime_start', 'b_number_start', 'p_uid_start',
       'p_bikes_start', 'p_lat_start', 'b_electric_lock_start',
       'b_bike_type_start', 'p_name_start', 'p_free_racks_start',
       'b_lock_types_start', 'p_number_start', 'p_lng_start',
       'b_boardcomputer_start', 'p_maintenance_start', 'p_bike_racks_end',
       'p_spot_end', 'p_booked_bikes_end', 'p_place_type_end', 'datetime_end',
       'p_uid_end', 'p_bikes_end', 'p_lat_end', 'p_name_end',
       'p_free_racks_end', 'p_number_end', 'p_lng_end', 'p_maintenance_end',
       'air_deg', 'air_hum', 'rain_mm', 'rain_yn', 'sun_hour', 'wind_ms',
       'month_start', 'month_end', 'day_start', 'day_end', 'day_of_week_start',
       'day_of_week_end', 'hour_start', 'hour_end', 'day_of_year_start',
       'day_of_year_end', 'season', 'weekend', 'booking_date_start',
       'trip_duration', 'idle_time', 'h3_hex_small_id_start',
       'h3_hex_small_id_end', 'h3_hex_big_id_start', 'h3_hex_big_id_end',
       '24_demand', '24_demand_hex_big', '24_demand_hex_small', '24_agg_time',
       '6_demand', '6_demand_hex_big', '6_demand_hex_small', '6_agg_time',
       '2_demand', '2_demand_hex_big', '2_demand_hex_small', '2_agg_time',
       '1_demand', '1_demand_hex_big', '1_demand_hex_small', '1_agg_time',
       '24_demand_end', '24_demand_hex_big_end', '24_demand_hex_small_end',
       '24_agg_time_end', '6_demand_end', '6_demand_hex_big_end',
       '6_demand_hex_small_end', '6_agg_time_end'],
      dtype='object')

In [114]:
# DELETE ME
df_trips = df_trips[["datetime_start", "datetime_end", "h3_hex_big_id_start", "h3_hex_big_id_end", "24_agg_time", "24_agg_time_end", "24_demand_hex_big", "24_demand_hex_big_end", "b_number_start"]].copy()

In [115]:
# df_trips["24_available_hex_big"] = df_trips["24_demand_hex_big_end"] - df_trips["24_demand_hex_big"]
# df_trips[df_trips["24_available_hex_big"] != 0]

In [116]:
df_current_hex = df_trips[df_trips["h3_hex_big_id_end"] == "881f1b4601fffff"]
df_current_hex.head(100)

,datetime_start,datetime_end,h3_hex_big_id_start,h3_hex_big_id_end,24_agg_time,24_agg_time_end,24_demand_hex_big,24_demand_hex_big_end,b_number_start
5,2019-01-20 00:07:00,2019-01-20 00:33:00,881f1b5591fffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,6,16,93440
8,2019-01-20 00:39:00,2019-01-20 00:45:00,881f1b4609fffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,7,16,93783
9,2019-01-20 00:33:00,2019-01-20 00:49:00,881f1b466bfffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,12,16,93785
25,2019-01-20 01:43:00,2019-01-20 01:51:00,881f1b466bfffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,12,16,93777
36,2019-01-20 03:05:00,2019-01-20 03:17:00,881f1b4643fffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,21,16,93028
...,...,...,...,...,...,...,...,...,...
1721,2019-01-23 19:37:00,2019-01-23 19:46:00,881f1b466bfffff,881f1b4601fffff,2019-01-23,2019-01-23 00:00:00,31,25,93700
1771,2019-01-23 21:43:00,2019-01-23 21:51:00,881f1b4609fffff,881f1b4601fffff,2019-01-23,2019-01-23 00:00:00,29,25,93257
1773,2019-01-23 21:54:00,2019-01-23 21:58:00,881f1b460dfffff,881f1b4601fffff,2019-01-23,2019-01-23 00:00:00,87,25,93502
1783,2019-01-23 22:26:00,2019-01-23 22:33:00,881f1b460dfffff,881f1b4601fffff,2019-01-23,2019-01-23 00:00:00,87,25,93701
1810,2019-01-24 02:10:00,2019-01-24 02:30:00,881f1b4601fffff,881f1b4601fffff,2019-01-24,2019-01-24 00:00:00,60,49,93691

In [117]:
df_end_before_agg_time = df_current_hex[df_current_hex["datetime_end"] < "2019-09-20"]
df_end_before_agg_time

,datetime_start,datetime_end,h3_hex_big_id_start,h3_hex_big_id_end,24_agg_time,24_agg_time_end,24_demand_hex_big,24_demand_hex_big_end,b_number_start
5,2019-01-20 00:07:00,2019-01-20 00:33:00,881f1b5591fffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,6,16,93440
8,2019-01-20 00:39:00,2019-01-20 00:45:00,881f1b4609fffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,7,16,93783
9,2019-01-20 00:33:00,2019-01-20 00:49:00,881f1b466bfffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,12,16,93785
25,2019-01-20 01:43:00,2019-01-20 01:51:00,881f1b466bfffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,12,16,93777
36,2019-01-20 03:05:00,2019-01-20 03:17:00,881f1b4643fffff,881f1b4601fffff,2019-01-20,2019-01-20 00:00:00,21,16,93028
...,...,...,...,...,...,...,...,...,...
417627,2019-09-19 19:53:00,2019-09-19 20:06:00,881f1b465dfffff,881f1b4601fffff,2019-09-19,2019-09-19 00:00:00,68,41,93841
417676,2019-09-19 20:43:00,2019-09-19 20:59:00,881f1b4669fffff,881f1b4601fffff,2019-09-19,2019-09-19 00:00:00,19,41,93866
417706,2019-09-19 21:31:00,2019-09-19 21:40:00,881f1b4643fffff,881f1b4601fffff,2019-09-19,2019-09-19 00:00:00,99,41,93757
417733,2019-09-19 22:25:00,2019-09-19 22:49:00,881f1b46e7fffff,881f1b4601fffff,2019-09-19,2019-09-19 00:00:00,1,41,93914
417737,2019-09-19 22:36:00,2019-09-19 22:58:00,881f1b54a3fffff,881f1b4601fffff,2019-09-19,2019-09-19 00:00:00,24,41,93697

In [118]:
bikes_before = df_end_before_agg_time.groupby("b_number_start")["datetime_end"].max().count()
bikes_before

578

In [119]:
df_start_before_agg_time_end = df_current_hex[df_current_hex["datetime_start"] > "2019-09-21"]
df_start_before_agg_time_end

,datetime_start,datetime_end,h3_hex_big_id_start,h3_hex_big_id_end,24_agg_time,24_agg_time_end,24_demand_hex_big,24_demand_hex_big_end,b_number_start
420045,2019-09-21 00:02:00,2019-09-21 00:10:00,881f1b4647fffff,881f1b4601fffff,2019-09-21,2019-09-21 00:00:00,31,21,93621
420063,2019-09-21 00:42:00,2019-09-21 00:54:00,881f1b4643fffff,881f1b4601fffff,2019-09-21,2019-09-21 00:00:00,129,21,93022
420072,2019-09-21 01:17:00,2019-09-21 01:46:00,881f1b4601fffff,881f1b4601fffff,2019-09-21,2019-09-21 00:00:00,24,21,93550
420092,2019-09-21 02:24:00,2019-09-21 02:48:00,881f1b54b1fffff,881f1b4601fffff,2019-09-21,2019-09-21 00:00:00,121,21,93402
420339,2019-09-21 10:24:00,2019-09-21 10:41:00,881f1b4643fffff,881f1b4601fffff,2019-09-21,2019-09-21 00:00:00,129,21,93358
...,...,...,...,...,...,...,...,...,...
567270,2020-01-20 19:12:00,2020-01-20 19:24:00,881f1b464bfffff,881f1b4601fffff,2020-01-20,2020-01-20 00:00:00,55,55,93064
567318,2020-01-20 19:53:00,2020-01-20 20:12:00,881f1b0965fffff,881f1b4601fffff,2020-01-20,2020-01-20 00:00:00,9,55,93834
567321,2020-01-20 19:50:00,2020-01-20 20:13:00,881f1b4601fffff,881f1b4601fffff,2020-01-20,2020-01-20 00:00:00,61,55,93915
567369,2020-01-20 21:16:00,2020-01-20 21:29:00,881f1b464bfffff,881f1b4601fffff,2020-01-20,2020-01-20 00:00:00,55,55,93055
567435,2020-01-20 23:29:00,2020-01-20 23:46:00,881f1b5593fffff,881f1b4601fffff,2020-01-20,2020-01-20 00:00:00,31,55,93908

In [120]:
bikes_used_in_agg_time = df_start_before_agg_time_end.groupby("b_number_start")["datetime_start"].count().count()
bikes_used_in_agg_time

530

In [121]:
idle_bikes = bikes_before - bikes_used_in_agg_time
idle_bikes

48

In [122]:
df_test = df_trips[(df_trips["h3_hex_big_id_end"] == "881f1b4601fffff") & (df_trips["24_agg_time"] == "2019-09-20")]
df_test

,datetime_start,datetime_end,h3_hex_big_id_start,h3_hex_big_id_end,24_agg_time,24_agg_time_end,24_demand_hex_big,24_demand_hex_big_end,b_number_start
417760,2019-09-20 00:02:00,2019-09-20 00:17:00,881f1b4649fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,77,48,93478
417763,2019-09-20 00:30:00,2019-09-20 00:56:00,881f1b54a7fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,55,48,93768
417764,2019-09-20 00:35:00,2019-09-20 00:59:00,881f1b54a7fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,55,48,93146
417765,2019-09-20 00:30:00,2019-09-20 00:59:00,881f1b54a7fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,55,48,93556
417766,2019-09-20 00:32:00,2019-09-20 00:59:00,881f1b54a7fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,55,48,93776
417767,2019-09-20 00:32:00,2019-09-20 01:00:00,881f1b54a7fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,55,48,93325
417769,2019-09-20 00:54:00,2019-09-20 01:09:00,881f1b464dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,5,48,93889
417771,2019-09-20 00:52:00,2019-09-20 01:10:00,881f1b5593fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,34,48,93850
417864,2019-09-20 06:34:00,2019-09-20 06:44:00,881f1b466bfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,41,48,93880
417891,2019-09-20 06:48:00,2019-09-20 07:03:00,881f1b465dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,77,48,93879
417895,2019-09-20 07:02:00,2019-09-20 07:14:00,881f1b4655fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,27,48,93072
417907,2019-09-20 07:17:00,2019-09-20 07:22:00,881f1b466bfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,41,48,93914
418015,2019-09-20 09:24:00,2019-09-20 09:30:00,881f1b460dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,59,48,93195
418050,2019-09-20 09:57:00,2019-09-20 10:02:00,881f1b460dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,59,48,93540
418156,2019-09-20 10:55:00,2019-09-20 10:57:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93146
418205,2019-09-20 10:55:00,2019-09-20 10:57:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93795
418236,2019-09-20 10:55:00,2019-09-20 10:57:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93540
418246,2019-09-20 10:55:00,2019-09-20 10:57:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93023
418317,2019-09-20 10:55:00,2019-09-20 10:57:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93697
418357,2019-09-20 10:55:00,2019-09-20 10:57:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93650
418395,2019-09-20 10:55:00,2019-09-20 10:57:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93606
418557,2019-09-20 10:59:00,2019-09-20 11:12:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93791
418599,2019-09-20 10:42:00,2019-09-20 11:35:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93846
418657,2019-09-20 11:55:00,2019-09-20 12:06:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93829
418700,2019-09-20 12:09:00,2019-09-20 12:22:00,881f1b4653fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,20,48,93850
418709,2019-09-20 10:49:00,2019-09-20 12:29:00,881f1b460dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,59,48,93060
418712,2019-09-20 12:22:00,2019-09-20 12:31:00,881f1b460dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,59,48,93791
418717,2019-09-20 12:17:00,2019-09-20 12:32:00,881f1b465dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,77,48,93430
418789,2019-09-20 12:52:00,2019-09-20 12:56:00,881f1b4603fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,18,48,93372
418829,2019-09-20 13:05:00,2019-09-20 13:16:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93691
418926,2019-09-20 13:49:00,2019-09-20 14:02:00,881f1b4651fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,30,48,93060
418958,2019-09-20 14:08:00,2019-09-20 14:17:00,881f1b460dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,59,48,93687
419024,2019-09-20 14:30:00,2019-09-20 14:48:00,881f1b0967fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,78,48,93745
419075,2019-09-20 14:57:00,2019-09-20 15:08:00,881f1b4603fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,18,48,93829
419077,2019-09-20 14:59:00,2019-09-20 15:09:00,881f1b4603fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,18,48,93023
419110,2019-09-20 15:09:00,2019-09-20 15:22:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93320
419117,2019-09-20 15:14:00,2019-09-20 15:29:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93829
419195,2019-09-20 15:58:00,2019-09-20 16:15:00,881f1b4651fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,30,48,93075
419343,2019-09-20 17:31:00,2019-09-20 17:54:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93829
419394,2019-09-20 18:20:00,2019-09-20 18:48:00,881f1b466bfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,41,48,93829
419492,2019-09-20 19:07:00,2019-09-20 19:10:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93829
419873,2019-09-20 19:42:00,2019-09-20 19:56:00,881f1b4645fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,16,48,93025
419880,2019-09-20 19:55:00,2019-09-20 20:06:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93775
419980,2019-09-20 22:03:00,2019-09-20 22:13:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93896
420009,2019-09-20 22:41:00,2019-09-20 22:50:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93465
420018,2019-09-20 19:31:00,2019-09-20 23:01:00,881f1b4605fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,7,48,93661
420019,2019-09-20 19:25:00,2019-09-20 23:02:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93829
420035,2019-09-20 23:20:00,2019-09-20 23:38:00,881f1b5593fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,34,48,93550

In [124]:
df_test["24_idle_bikes_hex_big"] = idle_bikes
df_test["24_available_hex_big"] = df_test["24_demand_hex_big_end"] - df_test["24_demand_hex_big"] + idle_bikes
df_test.tail(20)

C:\Users\Max\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Max\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,datetime_start,datetime_end,h3_hex_big_id_start,h3_hex_big_id_end,24_agg_time,24_agg_time_end,24_demand_hex_big,24_demand_hex_big_end,b_number_start,24_available_hex_big,24_idle_bikes_hex_big
418789,2019-09-20 12:52:00,2019-09-20 12:56:00,881f1b4603fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,18,48,93372,78,48
418829,2019-09-20 13:05:00,2019-09-20 13:16:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93691,-117,48
418926,2019-09-20 13:49:00,2019-09-20 14:02:00,881f1b4651fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,30,48,93060,66,48
418958,2019-09-20 14:08:00,2019-09-20 14:17:00,881f1b460dfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,59,48,93687,37,48
419024,2019-09-20 14:30:00,2019-09-20 14:48:00,881f1b0967fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,78,48,93745,18,48
419075,2019-09-20 14:57:00,2019-09-20 15:08:00,881f1b4603fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,18,48,93829,78,48
419077,2019-09-20 14:59:00,2019-09-20 15:09:00,881f1b4603fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,18,48,93023,78,48
419110,2019-09-20 15:09:00,2019-09-20 15:22:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93320,-117,48
419117,2019-09-20 15:14:00,2019-09-20 15:29:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93829,44,48
419195,2019-09-20 15:58:00,2019-09-20 16:15:00,881f1b4651fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,30,48,93075,66,48
419343,2019-09-20 17:31:00,2019-09-20 17:54:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93829,44,48
419394,2019-09-20 18:20:00,2019-09-20 18:48:00,881f1b466bfffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,41,48,93829,55,48
419492,2019-09-20 19:07:00,2019-09-20 19:10:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93829,44,48
419873,2019-09-20 19:42:00,2019-09-20 19:56:00,881f1b4645fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,16,48,93025,80,48
419880,2019-09-20 19:55:00,2019-09-20 20:06:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93775,-117,48
419980,2019-09-20 22:03:00,2019-09-20 22:13:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93896,-117,48
420009,2019-09-20 22:41:00,2019-09-20 22:50:00,881f1b4643fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,213,48,93465,-117,48
420018,2019-09-20 19:31:00,2019-09-20 23:01:00,881f1b4605fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,7,48,93661,89,48
420019,2019-09-20 19:25:00,2019-09-20 23:02:00,881f1b4601fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,52,48,93829,44,48
420035,2019-09-20 23:20:00,2019-09-20 23:38:00,881f1b5593fffff,881f1b4601fffff,2019-09-20,2019-09-20 00:00:00,34,48,93550,62,48